### ISSUE TITLE
Error event wrongly documented

### ISSUE THREAD

**Issue by yamsellem** [nathanoehlman/knox-mpu#35]
Readme [documents](https://github.com/nathanoehlman/knox-mpu#events) the `error` event as `Emitted each time a part upload fails. Passes an object containing the part id and error message`. 

This event is never emitted; looking at the source, it seems that this event proper name is `failed`.

**Comment by rhyslbw** [comment]
+1

**Comment by sgress454** [comment]
Fixed, thanks.
