### ISSUE TITLE
Keys with unicode characters are not properly uploaded

### ISSUE THREAD

**Issue by jrnt30** [nathanoehlman/knox-mpu#40]
When attempting to upload a file with unicode characters in the object name, knox-mpu will have an issue getting a properly authorization signature due to the interaction with the Knox client/auth. 

Ex. 
```
new MultiPartUpload({
  stream: readStream,
  objectName: 'someBucket/стра%на 1.csv',
  client: knoxClient,
}, function(err, data){
   console.log(err);
});
```

**Comment by sgress454** [comment]
Fixed by #41
