### ISSUE TITLE
Create tags for release since 0.1.7

### ISSUE THREAD

**Issue by yamsellem** [nathanoehlman/knox-mpu#43]
Can you please create the appropriate tags for release `0.1.7`, `0.1.8`, `0.1.9`, `0.1.10`, `0.1.11` and `0.2.0`?

Il will allow us to npm install them ;-).
Thanks.

**Comment by yamsellem** [comment]
Anyone?

**Comment by sgress454** [comment]
@yamsellem Sorry for the delay.  Pushed tags for everything except 0.1.7, which I couldn't find...

**Comment by yamsellem** [comment]
Thanks ^_^.
I guess this closes #31 as well.
